version: '3'
services:
     redis:
        image: redis:latest
        hostname: redis
        container_name: redis
        ports:
          - "6379:6379"
        volumes:
          - $HOME/redis:/data
          
     myapp:
        build: .  
        ports:
        - 8083:8080
        links:
        - "redis:redis"
        restart: "always"
