version: '3'
services:
     redis:
        image: redis:latest
        hostname: redis
        container_name: redis
        ports:
          - "6379:6379"
        volumes:
          - $HOME/redis:/data
     
     mongo:
        image: mongo:latest
        hostname: mongo
        container_name: mongo
        ports:
          - '27017:27017'
        volumes:
          - $HOME/mongodb:/data/db
          
     myapp:
        build: .  
        ports:
        - 8083:8080
        links:
        - "redis:redis"
        - "mongo:mongo"
        restart: "always"
